#yaml configuration on server site to pull data from my target servers
global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'

    static_configs:
      
      - targets: ['10.0.0.7:9100']
      - targets: ['10.0.0.9:9100']
      - targets: ['10.0.0.19:9100']
      - targets: ['10.0.0.6:9100']
      - targets: ['172.31.0.68:9100']
      - targets: ['172.31.15.233:9100']
